
REGION_ALIAS("REGION_TEXT", eflash);
REGION_ALIAS("REGION_RODATA", eflash);

REGION_ALIAS("REGION_DATA", ram_main);
REGION_ALIAS("REGION_BSS", ram_main);
REGION_ALIAS("REGION_HEAP", ram_main);
REGION_ALIAS("REGION_STACK", ram_main);
